import Head from 'next/head'
import { GetServerSideProps, GetStaticProps, NextPage } from "next";
import styles from "../styles/Home.module.css";
import { Dog } from '../data/@types/dogs';



const Home: NextPage<{ characters: Dog[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {characters.map((character) => {
        return (
         
            <h1 style={{padding: "100PX"}}>{character.name}</h1>
        
        );
      })}
    </div>
  );
};
export default Home ;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("http://localhost:3000/api/dogs");
  const results: Dog = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};